//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class college
    {
        public string CAMPUS { get; set; }
        public int CampusId { get; set; }
        public string YEAR { get; set; }
        public string CB0CT { get; set; }
        public string CB0CC { get; set; }
        public string CB0CS { get; set; }
        public string CB0CA { get; set; }
        public string CA0CT { get; set; }
        public string CA0CC { get; set; }
        public string CA0CS { get; set; }
        public string CA0CA { get; set; }
        public string CH0CT { get; set; }
        public string CH0CC { get; set; }
        public string CH0CS { get; set; }
        public string CH0CA { get; set; }
        public string CW0CT { get; set; }
        public string CW0CC { get; set; }
        public string CW0CS { get; set; }
        public string CW0CA { get; set; }
        public string CM0CT { get; set; }
        public string CM0CC { get; set; }
        public string CM0CS { get; set; }
        public string CM0CA { get; set; }
        public string CF0CT { get; set; }
        public string CF0CC { get; set; }
        public string CF0CS { get; set; }
        public string CF0CA { get; set; }
        public int id { get; set; }
    
        public virtual campusReference campusReference { get; set; }
    }
}
