//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mytable
    {
        public string CAMPUS { get; set; }
        public string CAMPNAME { get; set; }
        public string CNTYNAME { get; set; }
        public string COUNTY { get; set; }
        public string DISTNAME { get; set; }
        public string GRDSPAN { get; set; }
        public string GRDTYPE { get; set; }
    }
}
