//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class noner
    {
        public string CAMPUS { get; set; }
        public int CampusId { get; set; }
        public string YEAR { get; set; }
        public string CB0AT { get; set; }
        public string CA0AT { get; set; }
        public string CW0AT { get; set; }
        public string CH0AT { get; set; }
        public string CE0AT { get; set; }
        public string CL0AT { get; set; }
        public string CM0AT { get; set; }
        public string CF0AT { get; set; }
        public int id { get; set; }
    
        public virtual campusReference campusReference { get; set; }
    }
}
