//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class singleton : EntityBase
    {
        public string Id { get; set; }
        public string CAMPUS { get; set; }
        public string CAMPNAME { get; set; }
        public string CFLALTED { get; set; }
        public string CFLCHART { get; set; }
        public string CNTYNAME { get; set; }
        public string COUNTY { get; set; }
        public string DISTNAME { get; set; }
        public string DISTRICT { get; set; }
        public string GRDSPAN { get; set; }
        public string GRDTYPE { get; set; }
        public string LAT { get; set; }
        public string LNG { get; set; }
        public string CA00A001213R { get; set; }
        public string CB00A001213R { get; set; }
        public string CH00A001213R { get; set; }
        public string CW00A001213R { get; set; }
        public string YEAR { get; set; }
        public string CPEMALLP { get; set; }
        public string CPETALLC { get; set; }
        public string CPETBLAP { get; set; }
        public string CPETECOP { get; set; }
        public string CPETG01C { get; set; }
        public string CPETG01P { get; set; }
        public string CPETG02C { get; set; }
        public string CPETG02P { get; set; }
        public string CPETG03C { get; set; }
        public string CPETG03P { get; set; }
        public string CPETG04C { get; set; }
        public string CPETG04P { get; set; }
        public string CPETG05C { get; set; }
        public string CPETG05P { get; set; }
        public string CPETG06C { get; set; }
        public string CPETG06P { get; set; }
        public string CPETG07C { get; set; }
        public string CPETG07P { get; set; }
        public string CPETG08C { get; set; }
        public string CPETG08P { get; set; }
        public string CPETG09C { get; set; }
        public string CPETG09P { get; set; }
        public string CPETG10C { get; set; }
        public string CPETG10P { get; set; }
        public string CPETG11C { get; set; }
        public string CPETG11P { get; set; }
        public string CPETG12C { get; set; }
        public string CPETG12P { get; set; }
        public string CPETGKNC { get; set; }
        public string CPETGKNP { get; set; }
        public string CPETGPKC { get; set; }
        public string CPETGPKP { get; set; }
        public string CPETHISC { get; set; }
        public string CPETHISP { get; set; }
        public string CPETLEPC { get; set; }
        public string CPETLEPP { get; set; }
        public string CPETWHIC { get; set; }
        public string CPETWHIP { get; set; }
        public string CPST00FP { get; set; }
        public string CPST01FP { get; set; }
        public string CPST06FP { get; set; }
        public string CPST11FP { get; set; }
        public string CPST20FP { get; set; }
    }
}
