//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string CAMPUS { get; set; }
        public int CampusId { get; set; }
        public string YEAR { get; set; }
        public string CPST00FP { get; set; }
        public string CPST01FP { get; set; }
        public string CPST11FP { get; set; }
        public string CPST06FP { get; set; }
        public string CPST20FP { get; set; }
        public int id { get; set; }
    
        public virtual campusReference campusReference { get; set; }
    }
}
