//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string CAMPUS { get; set; }
        public int CampusId { get; set; }
        public string YEAR { get; set; }
        public string CPETHISP { get; set; }
        public string CPETBLAP { get; set; }
        public string CPETWHIP { get; set; }
        public string CPETLEPP { get; set; }
        public string CPETECOP { get; set; }
        public string CPETALLC { get; set; }
        public string CPERRAKR { get; set; }
        public string CPERRA1R { get; set; }
        public string CPERRA2R { get; set; }
        public string CPERRA3R { get; set; }
        public string CPERRA4R { get; set; }
        public string CPERRA5R { get; set; }
        public string CPERRA6R { get; set; }
        public string CPERRA7R { get; set; }
        public string CPERRA8R { get; set; }
        public int id { get; set; }
    
        public virtual campusReference campusReference { get; set; }
    }
}
